// This file is generated by `make gen-types` — do not hand-edit.
//
// Hand-written for now to match the locked API contract in SPEC.md exactly.
// `make gen-types` will overwrite it from shared/contracts/openapi.json.

export type AnalysisStatus = 'queued' | 'running' | 'done' | 'failed'

export type PipelineStep =
  | 'discovery'
  | 'kyc'
  | 'prompts'
  | 'execute'
  | 'footprint'
  | 'scoring'

export interface KYC {
  company: string
  description: string
  industry: string
  aliases: string[]
  products: string[]
  services: string[]
  keywords: string[]
  locations: string[]
  competitors: string[]
}

export interface Prompt {
  id: string
  text: string
  category: string
}

export interface AnalysisResponse {
  id: string
  prompt_id: string
  engine: string
  model: string
  raw_text: string
  footprint: boolean
  matched_snippet: string | null
  cost_usd: number
}

export interface AnalysisResult {
  kyc: KYC | null
  prompts: Prompt[]
  responses: AnalysisResponse[]
  geo_score: number | null
  footprint_count: number | null
  total_responses: number | null
}

export interface Analysis {
  id: string
  url: string
  status: AnalysisStatus
  progress: number
  current_step: PipelineStep | null
  error: string | null
  created_at: string
  updated_at: string
  result: AnalysisResult
}

export interface CreateAnalysisResponse {
  id: string
}
