/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Analysis */
        post: operations["submit_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Analysis */
        get: operations["read_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker */
        post: operations["submit_checker_api_v1_checker_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checker/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checker Lead */
        post: operations["submit_checker_lead_api_v1_checker_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Waitlist */
        post: operations["join_waitlist_api_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: string | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress */
            progress: number;
            result: components["schemas"]["ResultOut"];
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /** CheckerLeadRequest */
        CheckerLeadRequest: {
            /** Email */
            email: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CheckerSubmitRequest
         * @description A public checker submit. brand+category must be non-empty after trim.
         */
        CheckerSubmitRequest: {
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /**
             * Lang
             * @default en
             */
            lang: string;
        };
        /** CheckerSubmitResponse */
        CheckerSubmitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /**
         * CompetitorMention
         * @description A competitor brand that showed up in the answers and how many answers
         *     named it (P5.3) — a proper-noun co-mention over the raw text, not the KYC
         *     competitor list.
         */
        CompetitorMention: {
            /** Mentions */
            mentions: number;
            /** Name */
            name: string;
        };
        /** CreateAnalysisRequest */
        CreateAnalysisRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** CreateAnalysisResponse */
        CreateAnalysisResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * EnginePresence
         * @description One engine's presence in a checker run: ``mentioned`` of ``total`` answers
         *     named the searched brand (P5.3). Read-time aggregate of the ``footprint``
         *     booleans; the per-engine totals sum to ``total_responses``.
         */
        EnginePresence: {
            /** Engine */
            engine: string;
            /** Mentioned */
            mentioned: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PromptOut */
        PromptOut: {
            /** Category */
            category: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /** ResponseOut */
        ResponseOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Engine */
            engine: string;
            /** Footprint */
            footprint: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Snippet */
            matched_snippet: string | null;
            /** Model */
            model: string;
            /**
             * Prompt Id
             * Format: uuid
             */
            prompt_id: string;
            /** Raw Text */
            raw_text: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Competitors Appeared */
            competitors_appeared: components["schemas"]["CompetitorMention"][] | null;
            /** Engine Presence */
            engine_presence: components["schemas"]["EnginePresence"][] | null;
            /** Footprint Count */
            footprint_count: number | null;
            /** Geo Score */
            geo_score: number | null;
            /** Kyc */
            kyc: {
                [key: string]: unknown;
            } | null;
            /** Prompts */
            prompts: components["schemas"]["PromptOut"][];
            /** Responses */
            responses: components["schemas"]["ResponseOut"][];
            /** Total Responses */
            total_responses: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaitlistRequest
         * @description A public waitlist signup. The email is validated + normalized server-side
         *     (trim + lowercase) so a malformed address is a 422 before any row is written,
         *     and the stored value matches the unique lowercased column.
         */
        WaitlistRequest: {
            /** Email */
            email: string;
        };
        /** WaitlistResponse */
        WaitlistResponse: {
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_api_v1_checker_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checker_lead_api_v1_checker_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_api_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
